import sdk from '@stackblitz/sdk';
import { useEffect, useRef } from 'react';
import { GeneratingPreview } from './GeneratingPreview';

interface StackBlitzPreviewProps {
  projectFiles: Record<string, string>;
  isDark?: boolean;
  onConsoleLog?: (log: { level: 'log' | 'error' | 'warn'; message: string }) => void;
}

export function StackBlitzPreview({ projectFiles, isDark = false }: StackBlitzPreviewProps) {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!containerRef.current || !projectFiles || Object.keys(projectFiles).length === 0) {
      return;
    }

    console.log('🚀 StackBlitz - Initialisation avec', Object.keys(projectFiles).length, 'fichiers');
    console.log('📦 Fichiers:', Object.keys(projectFiles));

    // Détecter le type de projet
    const isReactProject = Object.keys(projectFiles).some(path => 
      path.includes('App.tsx') || 
      path.includes('App.jsx') || 
      path.includes('main.tsx') || 
      path.includes('main.jsx') ||
      path.includes('package.json')
    );

    const template = isReactProject ? 'node' : 'html';
    
    // Trouver le fichier d'entrée
    const entryFile = isReactProject 
      ? (Object.keys(projectFiles).find(f => f.includes('main.tsx')) || 
         Object.keys(projectFiles).find(f => f.includes('App.tsx')) || 
         'src/main.tsx')
      : 'index.html';

    console.log('🎯 Template:', template);
    console.log('🎯 Entry file:', entryFile);

    sdk.embedProject(
      containerRef.current,
      {
        title: 'Magellan Generated App',
        description: 'App generated by MagellanLabs',
        template,
        files: projectFiles,
      },
      {
        height: '100%',
        openFile: entryFile,
        view: 'preview',
        theme: isDark ? 'dark' : 'light',
        hideExplorer: true,
        hideNavigation: false,
        forceEmbedLayout: true,
      }
    );
  }, [projectFiles, isDark]);

  if (!projectFiles || Object.keys(projectFiles).length === 0) {
    return <GeneratingPreview />;
  }

  return (
    <div 
      ref={containerRef} 
      className="w-full h-full rounded-xl overflow-hidden"
      style={{ minHeight: '600px' }}
    />
  );
}
